name: GitHub Actions Demo
on: 
  push:
    branches:
      -main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
    workflow_dispatch:
      schedule:
        cron: '0 6 * * 0' 

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    -name: Checkout 
  
